version: "3.9"
services:
  PI-Django:
    build: .
    volumes:
    - .:/estagio
    ports:
      - 80:8000
    image: python
    container_name: PI-Django
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
  #   depends_on:
  #     - database
  
  # database:
  #   image: postgres
  #   container_name: django-postgres
  #   volumes:
  #     - ./data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   ports:
  #     - 5432:5432
